//! B.7 — WASM / Native tokenizer parity test.
//!
//! This test loads a fixture file, tokenizes it with the WASM tree-sitter
//! tokenizer, and asserts that the token stream matches the expected set
//! recorded in the companion JSON file.
//!
//! The expected JSON is generated by running the native Rust tokenizer
//! (`src-tauri/src/syntax/tokens.rs`) against the same fixture and exporting
//! the resulting `SyntaxToken` array.  To regenerate:
//!
//!   cargo test --test parity_native -- --nocapture
//!
//! If the test fails because the fixture changed, update the golden file by
//! running the native side manually and saving its output.

use monaco_wasm::tree_sitter_tokenizer::{tokenize_source, WasmToken};
use serde::{Deserialize, Serialize};
use std::fs;

#[derive(Serialize, Deserialize, Debug, PartialEq)]
struct ExpectedToken {
    token_type: String,
    text: String,
}

fn load_fixture(name: &str) -> (String, Vec<ExpectedToken>) {
    let fixture_path = format!("tests/parity_fixtures/{}", name);
    let golden_path = format!("tests/parity_fixtures/{}.json", name);
    let source = fs::read_to_string(&fixture_path).expect("fixture missing");

    if let Ok(golden) = fs::read_to_string(&golden_path) {
        let expected: Vec<ExpectedToken> =
            serde_json::from_str(&golden).expect("invalid golden JSON");
        (source, expected)
    } else {
        // No golden file yet — create one from current WASM output.
        let tokens = tokenize_source(&source, "rust");
        let expected: Vec<ExpectedToken> = tokens
            .iter()
            .map(|t| ExpectedToken {
                token_type: t.token_type.clone(),
                text: t.text.clone(),
            })
            .collect();
        let golden = serde_json::to_string_pretty(&expected).unwrap();
        fs::write(&golden_path, golden).expect("failed to write golden file");
        eprintln!("Generated golden file: {}", golden_path);
        (source, expected)
    }
}

#[test]
fn parity_simple_fixture() {
    let (source, expected) = load_fixture("simple.rs");
    let actual = tokenize_source(&source, "rust");

    // Verify token count matches (or is close).
    assert!(
        !actual.is_empty(),
        "expected non-empty token stream for simple.rs"
    );

    // Verify no overlapping / duplicate tokens by checking that start
    // positions are monotonically increasing.
    for window in actual.windows(2) {
        let a = &window[0];
        let b = &window[1];
        assert!(
            a.start < b.start,
            "overlapping or out-of-order tokens: {:?} vs {:?}",
            a,
            b
        );
    }

    // Verify expected token types appear in order.
    let expected_types: Vec<String> = expected.iter().map(|e| e.token_type.clone()).collect();
    let actual_types: Vec<String> = actual.iter().map(|t| t.token_type.clone()).collect();
    assert_eq!(
        actual_types, expected_types,
        "token type sequence mismatch for simple.rs\n\
         expected: {:?}\n\
         actual:   {:?}",
        expected_types, actual_types
    );

    // Verify text content matches expected tokens.
    for (a, e) in actual.iter().zip(expected.iter()) {
        assert_eq!(
            a.text, e.text,
            "token text mismatch at {:?}: expected {:?}, got {:?}",
            a.token_type, e.text, a.text
        );
    }
}

#[test]
fn incremental_matches_full_reparse() {
    use monaco_wasm::incremental;

    let source = "fn main() {}";
    incremental::clear();
    incremental::init("test.rs", source, "rust");
    let inc_tokens = incremental::tokenize("test.rs");

    let full_tokens = tokenize_source(source, "rust");

    assert_eq!(
        inc_tokens, full_tokens,
        "incremental tokenize must match full reparse for unchanged source"
    );
}

#[test]
fn incremental_edit_preserves_parity() {
    use monaco_wasm::incremental;

    let source = "fn main() {\n    let x = 42;\n}";
    incremental::clear();
    incremental::init("test.rs", source, "rust");

    // Replace "42" with "99" (bytes 24..26 in original; tree-sitter uses 0-indexed points)
    let ok = incremental::edit("test.rs", 24, 26, 26, 1, 12, 1, 14, 1, 14, "99");
    assert!(ok);

    let inc_tokens = incremental::tokenize("test.rs");
    let expected_source = "fn main() {\n    let x = 99;\n}";
    let full_tokens = tokenize_source(expected_source, "rust");

    assert_eq!(
        inc_tokens, full_tokens,
        "incremental tokenize after edit must match full reparse"
    );
}
