[package]
name = "monaco-tauri-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.monaco-tauri]
path = ".."

[[bin]]
name = "fuzz_apply_change"
path = "fuzz_targets/fuzz_apply_change.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_tokenize"
path = "fuzz_targets/fuzz_tokenize.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_compute_line_delta"
path = "fuzz_targets/fuzz_compute_line_delta.rs"
test = false
doc = false
bench = false
